FROM ##from_image##
MAINTAINER mdye <mdye@us.ibm.com>

RUN mkdir -p /usr/local/synchrophasor
ADD ./synchrophasor-publisher /usr/local/synchrophasor/
ADD ./VERSION /usr/local/synchrophasor/

WORKDIR /usr/local/synchrophasor
CMD ["./synchrophasor-publisher", "-v", "3", "-logtostderr"]
